/**
 * GenPass — Données statiques
 *
 * Ce fichier centralise les données de configuration et la wordlist.
 * Séparé de script.js pour faciliter la maintenance : ajouter des mots,
 * modifier les jeux de caractères ou ajuster la config sans toucher à la logique.
 *
 * Doit être inclus AVANT script.js dans index.html.
 */

/* ===== Configuration des jeux de caractères ===== */

/**
 * Jeux de caractères disponibles pour la génération aléatoire.
 * Exposé globalement (window scope) pour être consommé par script.js.
 */
export const CONFIG = {
  lowercase: "abcdefghijklmnopqrstuvwxyz",
  uppercase: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  numbers: "0123456789",
  symbols: "!@#$%^&*()_+-=[]{}|;:,.<>?",
};

/* ===== Wordlist pour le mode mémorable ===== */

/**
 * Liste de ~511 mots français courts et mémorables.
 *
 * Critères de sélection :
 *   – Sans accents (compatibilité ASCII, aisance de saisie sur toutes dispositions)
 *   – Longueur ≤ 10 caractères
 *   – Connus, évocateurs, faciles à visualiser mentalement
 *
 * Entropie avec 3 mots + 1 chiffre par mot (défaut) :
 *   500³ × 10³ ≈ 1,25 × 10¹¹ combinaisons → ~37 bits
 *   (vs ~28 bits avec la liste de 64 mots précédente)
 *
 * Exposé globalement pour être consommé par script.js.
 */
export const WORDS_FR = [
  /* ------------------------------------------------------------------ */
  /* Nature & Paysages (125 mots)                                        */
  /* ------------------------------------------------------------------ */
  "Abime",
  "Arbre",
  "Ardoise",
  "Atoll",
  "Aurore",
  "Avalanche",
  "Azur",
  "Balcon",
  "Banquise",
  "Basalte",
  "Bassin",
  "Bayou",
  "Blizzard",
  "Boreal",
  "Bosquet",
  "Braise",
  "Brousse",
  "Brume",
  "Buisson",
  "Butte",
  "Caillou",
  "Canyon",
  "Cascade",
  "Caverne",
  "Chemin",
  "Ciel",
  "Cime",
  "Cirque",
  "Citron",
  "Clairiere",
  "Colline",
  "Coral",
  "Cristal",
  "Cumulus",
  "Cyclone",
  "Desert",
  "Dune",
  "Eboulis",
  "Eclair",
  "Estuaire",
  "Etang",
  "Etoile",
  "Falaise",
  "Faille",
  "Feuille",
  "Fjord",
  "Fleuve",
  "Foret",
  "Fraise",
  "Garrigue",
  "Geyser",
  "Glacier",
  "Gorge",
  "Gouffre",
  "Granit",
  "Greve",
  "Grotte",
  "Herbe",
  "Horizon",
  "Ile",
  "Ilot",
  "Jardin",
  "Jungle",
  "Karst",
  "Kayak",
  "Lac",
  "Lagon",
  "Lagune",
  "Lande",
  "Lave",
  "Limon",
  "Lune",
  "Maquis",
  "Marais",
  "Marbre",
  "Mesa",
  "Mistral",
  "Moisson",
  "Montagne",
  "Moraine",
  "Morne",
  "Mousse",
  "Mousson",
  "Nappe",
  "Nebule",
  "Nuage",
  "Oasis",
  "Ocean",
  "Opale",
  "Orage",
  "Oued",
  "Pampa",
  "Paturage",
  "Perle",
  "Phare",
  "Pierre",
  "Plaine",
  "Prairie",
  "Pluie",
  "Puy",
  "Quartz",
  "Ravin",
  "Recif",
  "Rivage",
  "Riviere",
  "Roche",
  "Ruisseau",
  "Sable",
  "Sapin",
  "Savane",
  "Schiste",
  "Sillon",
  "Soleil",
  "Sommet",
  "Steppe",
  "Talus",
  "Tempete",
  "Terrasse",
  "Tornade",
  "Torrent",
  "Toundra",
  "Vague",
  "Vallee",
  "Vallon",
  "Verglas",
  "Versant",
  "Volcan",
  "Voute",

  /* ------------------------------------------------------------------ */
  /* Animaux (125 mots)                                                  */
  /* ------------------------------------------------------------------ */
  "Aigle",
  "Aigrette",
  "Albatros",
  "Alcyon",
  "Alouette",
  "Antilope",
  "Ara",
  "Autruche",
  "Baleine",
  "Belette",
  "Biche",
  "Bison",
  "Bongo",
  "Bouquetin",
  "Buffle",
  "Butor",
  "Caille",
  "Calao",
  "Canard",
  "Capybara",
  "Caracal",
  "Castor",
  "Casuar",
  "Cerf",
  "Chacal",
  "Chamois",
  "Cigogne",
  "Civette",
  "Coati",
  "Cobra",
  "Condor",
  "Corbeau",
  "Couguar",
  "Coyote",
  "Dindon",
  "Dingo",
  "Ecureuil",
  "Emeu",
  "Faucon",
  "Fennec",
  "Flamant",
  "Fouine",
  "Furet",
  "Galago",
  "Gavial",
  "Gazelle",
  "Geai",
  "Gecko",
  "Genette",
  "Glouton",
  "Gorille",
  "Grebe",
  "Grizzly",
  "Grue",
  "Guepard",
  "Harfang",
  "Hermine",
  "Heron",
  "Hibou",
  "Huard",
  "Husky",
  "Ibis",
  "Ibex",
  "Iguane",
  "Impala",
  "Jaguar",
  "Kinkajou",
  "Koala",
  "Lamantin",
  "Lapin",
  "Lemur",
  "Leopard",
  "Loutre",
  "Loup",
  "Lynx",
  "Macaque",
  "Manchot",
  "Mandrill",
  "Marmot",
  "Marsouin",
  "Merle",
  "Merou",
  "Milan",
  "Mouflon",
  "Musaraigne",
  "Nandou",
  "Narval",
  "Nautile",
  "Ocelot",
  "Okapi",
  "Opossum",
  "Orca",
  "Orignal",
  "Ours",
  "Panda",
  "Panthere",
  "Paon",
  "Pingouin",
  "Piranha",
  "Poulain",
  "Puma",
  "Putois",
  "Raton",
  "Raven",
  "Renard",
  "Salamandre",
  "Sanglier",
  "Saumon",
  "Scorpion",
  "Serpent",
  "Spatule",
  "Suricate",
  "Tamarin",
  "Tapir",
  "Tatou",
  "Tetras",
  "Tigre",
  "Toucan",
  "Varan",
  "Vautour",
  "Vervet",
  "Wapiti",
  "Yak",
  "Zebre",
  "Zorille",

  /* ------------------------------------------------------------------ */
  /* Objets & Technologie (78 mots)                                      */
  /* ------------------------------------------------------------------ */
  "Ancre",
  "Armure",
  "Atlas",
  "Axe",
  "Balise",
  "Barre",
  "Baton",
  "Boussole",
  "Burin",
  "Cable",
  "Cadran",
  "Capteur",
  "Carte",
  "Chaine",
  "Circuit",
  "Clavier",
  "Clef",
  "Codex",
  "Compas",
  "Corde",
  "Crayon",
  "Cube",
  "Curseur",
  "Dague",
  "Dalle",
  "Digit",
  "Disque",
  "Drone",
  "Filtre",
  "Flux",
  "Forge",
  "Graphe",
  "Grille",
  "Jauge",
  "Jeton",
  "Laser",
  "Lentille",
  "Levier",
  "Matrice",
  "Mire",
  "Nexus",
  "Noyau",
  "Octet",
  "Orbite",
  "Pixel",
  "Pivot",
  "Radar",
  "Rayon",
  "Relais",
  "Reseau",
  "Signal",
  "Sonde",
  "Spectre",
  "Tamis",
  "Toile",
  "Turbine",
  "Vecteur",
  "Vortex",
  "Aimant",
  "Arche",
  "Arceau",
  "Bascule",
  "Cabestan",
  "Crochet",
  "Enclume",
  "Fuseau",
  "Gabarit",
  "Gouvernail",
  "Hamecon",
  "Mandrin",
  "Moufle",
  "Passerelle",
  "Piston",
  "Poulie",
  "Ressort",
  "Rivet",
  "Treillis",
  "Treuil",

  /* ------------------------------------------------------------------ */
  /* Sciences & Nature abstraite (70 mots)                               */
  /* ------------------------------------------------------------------ */
  "Apex",
  "Axone",
  "Base",
  "Beta",
  "Biome",
  "Brin",
  "Chrome",
  "Cible",
  "Codon",
  "Comet",
  "Cortex",
  "Delta",
  "Ellipse",
  "Enzyme",
  "Ether",
  "Fibre",
  "Focus",
  "Gene",
  "Globe",
  "Gradient",
  "Helix",
  "Ion",
  "Isotope",
  "Locus",
  "Magma",
  "Molecule",
  "Neurone",
  "Onde",
  "Phase",
  "Photon",
  "Planet",
  "Plasma",
  "Pole",
  "Proton",
  "Quasar",
  "Secteur",
  "Serum",
  "Sinus",
  "Spore",
  "Synapse",
  "Tenseur",
  "Voxel",
  "Zenith",
  "Zephyr",
  "Zone",
  "Zygote",
  "Genome",
  "Allele",
  "Gamete",
  "Flagelle",
  "Mitose",
  "Dendrite",
  "Bactum",
  "Electron",
  "Photino",
  "Boson",
  "Fermion",
  "Tachyon",
  "Muon",
  "Quark",
  "Gluon",
  "Lepton",
  "Meson",
  "Baryon",
  "Hadron",
  "Nebula",
  "Pulsar",
  "Supernova",
  "Redshift",
  "Parsec",

  /* ------------------------------------------------------------------ */
  /* Concepts & Quotidien (110 mots)                                     */
  /* ------------------------------------------------------------------ */
  "Abri",
  "Acier",
  "Aile",
  "Angle",
  "Anneau",
  "Arc",
  "Art",
  "Assaut",
  "Aura",
  "Bague",
  "Bande",
  "Bastion",
  "Bilan",
  "Bord",
  "Borne",
  "Brise",
  "Cage",
  "Calme",
  "Cap",
  "Cave",
  "Chasse",
  "Choc",
  "Chute",
  "Clan",
  "Coin",
  "Col",
  "Cone",
  "Coupe",
  "Cycle",
  "Debut",
  "Degre",
  "Defi",
  "Dome",
  "Donjon",
  "Ecran",
  "Elan",
  "Epee",
  "Etat",
  "Exploit",
  "Face",
  "Feu",
  "Fil",
  "Flot",
  "Force",
  "Fort",
  "Foudre",
  "Garde",
  "Geste",
  "Graal",
  "Guide",
  "Halo",
  "Hameau",
  "Jeu",
  "Lame",
  "Lance",
  "Legende",
  "Lien",
  "Lion",
  "Logis",
  "Main",
  "Masse",
  "Menhir",
  "Metal",
  "Mode",
  "Monde",
  "Mur",
  "Mythe",
  "Nid",
  "Noeud",
  "Nuit",
  "Oracle",
  "Ordre",
  "Outil",
  "Pacte",
  "Pari",
  "Piste",
  "Plan",
  "Pont",
  "Prisme",
  "Prise",
  "Race",
  "Rang",
  "Recul",
  "Refuge",
  "Regle",
  "Rempart",
  "Role",
  "Rond",
  "Route",
  "Rubis",
  "Rythme",
  "Saphir",
  "Sens",
  "Sentier",
  "Seuil",
  "Site",
  "Source",
  "Sport",
  "Style",
  "Table",
  "Titre",
  "Trace",
  "Tube",
  "Unite",
  "Valeur",
  "Vestige",
  "Vide",
  "Vie",
  "Voie",
  "Vue",
];

/* ===== Citations & Proverbes pour le mode "Phrase connue" ===== */

/**
 * Collection de citations, proverbes, vers célèbres et expressions populaires.
 * Utilisée par le mode "Phrase connue" pour générer des passphrases mémorables.
 *
 * Critères de sélection :
 *   – Phrases célèbres, facilement reconnaissables
 *   – Sans accents (compatibilité ASCII)
 *   – Assez longues pour en extraire 3-8 mots-clés
 *   – Domaine public ou expressions courantes
 *
 * Chaque entrée : { text: "phrase complète", author: "auteur" }
 */
export const QUOTES_FR = [
  /* --- Citations classiques & philosophie --- */
  {
    text: "La beaute est dans les yeux de celui qui regarde",
    author: "Oscar Wilde",
  },
  { text: "Je pense donc je suis", author: "Descartes" },
  {
    text: "Le coeur a ses raisons que la raison ne connait point",
    author: "Pascal",
  },
  { text: "Il faut imaginer Sisyphe heureux", author: "Albert Camus" },
  { text: "Connais-toi toi-meme", author: "Socrate" },
  {
    text: "La simplicite est la sophistication supreme",
    author: "Leonard de Vinci",
  },
  {
    text: "Rien ne se perd rien ne se cree tout se transforme",
    author: "Lavoisier",
  },
  {
    text: "Un pour tous tous pour un c est notre devise",
    author: "Alexandre Dumas",
  },
  {
    text: "Tout ce qui ne nous tue pas nous rend plus fort",
    author: "Nietzsche",
  },
  {
    text: "La liberte des uns commence ou finit celle des autres",
    author: "John Stuart Mill",
  },
  {
    text: "Celui qui deplace la montagne commence par deplacer les petites pierres",
    author: "Confucius",
  },
  {
    text: "La vie est un sommeil dont l amour est le reve",
    author: "Alfred de Musset",
  },
  {
    text: "Le savoir est la seule matiere qui s accroit quand on la partage",
    author: "Socrate",
  },
  { text: "Ce qui se concoit bien s enonce clairement", author: "Boileau" },
  {
    text: "Il n est pas de vent favorable pour celui qui ne sait pas ou il va",
    author: "Seneque",
  },
  {
    text: "La culture c est ce qui reste quand on a tout oublie",
    author: "Edouard Herriot",
  },

  /* --- Proverbes français --- */
  { text: "Qui vivra verra", author: "Proverbe" },
  { text: "Apres la pluie le beau temps", author: "Proverbe" },
  { text: "Pierre qui roule n amasse pas mousse", author: "Proverbe" },
  { text: "L habit ne fait pas le moine", author: "Proverbe" },
  { text: "Mieux vaut tard que jamais", author: "Proverbe" },
  { text: "La vengeance est un plat qui se mange froid", author: "Proverbe" },
  { text: "Qui seme le vent recolte la tempete", author: "Proverbe" },
  { text: "A coeur vaillant rien d impossible", author: "Proverbe" },
  { text: "Chat echaude craint l eau froide", author: "Proverbe" },
  {
    text: "Il ne faut pas vendre la peau de l ours avant de l avoir tue",
    author: "Proverbe",
  },
  { text: "Qui ne risque rien n a rien", author: "Proverbe" },
  { text: "L union fait la force", author: "Proverbe" },
  { text: "Tel pere tel fils", author: "Proverbe" },
  { text: "Petit a petit l oiseau fait son nid", author: "Proverbe" },
  { text: "Les murs ont des oreilles", author: "Proverbe" },
  { text: "Tout vient a point a qui sait attendre", author: "Proverbe" },
  { text: "Vouloir c est pouvoir", author: "Proverbe" },
  {
    text: "On ne fait pas d omelette sans casser des oeufs",
    author: "Proverbe",
  },
  { text: "Il faut battre le fer tant qu il est chaud", author: "Proverbe" },
  { text: "Un homme averti en vaut deux", author: "Proverbe" },

  /* --- Poesie & Litterature --- */
  {
    text: "Demain des l aube a l heure ou blanchit la campagne",
    author: "Victor Hugo",
  },
  {
    text: "Heureux qui comme Ulysse a fait un beau voyage",
    author: "Joachim du Bellay",
  },
  {
    text: "La chair est triste helas et j ai lu tous les livres",
    author: "Mallarme",
  },
  {
    text: "Je suis le tenebreux le veuf l inconsole",
    author: "Gerard de Nerval",
  },
  {
    text: "Sous le pont Mirabeau coule la Seine et nos amours",
    author: "Apollinaire",
  },
  {
    text: "Le temps a laisse son manteau de vent de froidure et de pluie",
    author: "Charles d Orleans",
  },
  { text: "La terre est bleue comme une orange", author: "Paul Eluard" },
  {
    text: "Il pleure dans mon coeur comme il pleut sur la ville",
    author: "Verlaine",
  },
  {
    text: "O temps suspends ton vol et vous heures propices",
    author: "Lamartine",
  },
  { text: "Les sanglots longs des violons de l automne", author: "Verlaine" },

  /* --- Expressions celebres --- */
  { text: "Paris vaut bien une messe", author: "Henri IV" },
  { text: "L etat c est moi", author: "Louis XIV" },
  { text: "Impossible n est pas francais", author: "Napoleon" },
  {
    text: "Je suis le maitre de mon destin le capitaine de mon ame",
    author: "William Henley",
  },
  {
    text: "Science sans conscience n est que ruine de l ame",
    author: "Rabelais",
  },
  {
    text: "Le monde est un livre et ceux qui ne voyagent pas n en lisent qu une page",
    author: "Saint Augustin",
  },
  {
    text: "La plume est plus forte que l epee",
    author: "Edward Bulwer-Lytton",
  },
  {
    text: "Il n y a pas de hasard il n y a que des rendez-vous",
    author: "Paul Eluard",
  },
  {
    text: "Le bonheur est parfois cache dans l inconnu",
    author: "Victor Hugo",
  },
  { text: "Les grandes pensees viennent du coeur", author: "Vauvenargues" },

  /* --- Citations modernes & universelles --- */
  {
    text: "La folie c est de faire toujours la meme chose et d attendre un resultat different",
    author: "Albert Einstein",
  },
  {
    text: "Soyez le changement que vous voulez voir dans le monde",
    author: "Gandhi",
  },
  {
    text: "La vie c est ce qui arrive quand on est occupe a faire d autres projets",
    author: "John Lennon",
  },
  {
    text: "Il faut toujours viser la lune car meme en cas d echec on atterrit dans les etoiles",
    author: "Oscar Wilde",
  },
  {
    text: "Le courage n est pas l absence de peur mais la capacite de vaincre ce qui fait peur",
    author: "Nelson Mandela",
  },
  {
    text: "Un voyage de mille lieues commence toujours par un premier pas",
    author: "Lao Tseu",
  },
  { text: "Les apparences sont souvent trompeuses", author: "Esope" },
  {
    text: "Le plus grand voyageur n est pas celui qui a fait dix fois le tour du monde",
    author: "Gandhi",
  },
  {
    text: "Dans la vie rien n est a craindre tout est a comprendre",
    author: "Marie Curie",
  },
  {
    text: "La seule facon de faire du bon travail c est d aimer ce que l on fait",
    author: "Steve Jobs",
  },
];
